version: 2
updates:
    # Maintain dependencies for Composer
    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "weekly"
      versioning-strategy: increase-if-necessary
